# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='created_trips', to='travel_buddy.User'),
            preserve_default=False,
        ),
    ]
